name: Deploy to GitHub Container Registry

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Publish Docker Images
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write


    steps:
      - name: Checkout head
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: Read version from file
        id: get_version
        run: echo "VERSION=$(cat version.txt)" >> $GITHUB_ENV

      - name: Echo metadata
        run: |
          echo "version: ${{ env.VERSION }}"
          echo "sha: ${{ github.sha }}"

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ env.VERSION }}
            ghcr.io/${{ github.repository }}:${{ github.sha }}
          build-args: |
            VERSION=${{ env.VERSION }}

      - name: Log out from GitHub Container Registry
        run: docker logout ghcr.io